### PR TITLE
Feature: auto value for max queued seeds

### PR DESCRIPTION
**Pull request by Crystal15118**
it will probably be very similar to how [PR#62](https://github.com/KingContaria/seedqueue/pull/62) implements auto value for `SeedQueueConfig#backgroundPreviews`

### CODE REVIEW

**Comment by KingContaria** [comment]
I don't think this is necessary, AUTO should only really be used for options that users don't need to understand, but to increase their RAM allocation in the first place users should in my opinion understand that this is going to correlate with Max Queued Seeds.
I also don't want SeedQueue to be on (Max Queued Seeds != 0) by default.
Something I would be interested in is implementing reasonable defaults for Max Generating Seeds and Max Generating Seeds (Wall) once we get the results from the poll in discord.
Unless you come up with a very convincing argument I think I'll close this pr

**Comment by Crystal15118** [comment]
> I don't think this is necessary
Many users have been seen to have Max Queued Seeds much below what it should be with the ram they've allocated thinking that it would cause issues because their cpu isn't "good enough" (this feature would had prevented that and also the text walls helpers had to send to those users to pin-point the best settings would had reduced in length)
> AUTO should only really be used for options that users don't need to understand
Why? imo we should have AUTO value for every option we can. Why you may ask, because it would make helping new users much much easier in general (reducing the amount of support we have to do can increase our productivity towards more features, fixes and improvements --> right now if someone asks for the best settings for their specs we have to explain so many things for Max Queued Seeds option)
> I also don't want SeedQueue to be on (Max Queued Seeds != 0) by default
We can set it to 0 (as i said above just telling the user to set it to Auto would be much easier than explaining everything to them when we know that they will most likely put it on what Auto does)

**Comment by Crystal15118** [comment]
another thing is that why do you think Max Generating Seeds and Max Generating Seeds (Wall) are options people don't need to understand? imo they should be explained even prior to Max Queued Seeds and most people will want to understand them if they knew what they are but the same doesn't really go for Max Queued Seeds.

**Comment by KingContaria** [comment]
I think defaults are fine for Max Generating Seeds (+Wall) to give users a starting point to try out more themselves. I absolutely think they are settings people need to understand, thats why I'm against making them AUTO.
I only really want to use AUTO values where users shouldn't mess with stuff unless they know something already (see Threading Settings) or where a default value wouldn't work because it changes depending on more factors (Background Previews, changes based on other options/layouts).
I'm opposed to AUTO values anywhere in Queue Settings to be honest, because I think those are the options users should kind of understand.
What I'm not opposed to however would be to implement some kind of warning for users based on their allocation, however there would also have to be a good bit of tolerance, for example AA runners usually use 3GB as base

**Comment by Crystal15118** [comment]
> I think defaults are fine for Max Generating Seeds (+Wall) to give users a starting point to try out more themselves. I absolutely think they are settings people need to understand, thats why I'm against making them AUTO

😕 you just said "I would be interested in is implementing reasonable defaults for Max Generating Seeds and Max Generating Seeds (Wall)"

> I'm opposed to AUTO values anywhere in Queue Settings to be honest, because I think those are the options users should kind of understand.

Making the user understand what it is just a sentence long, making them put it to what it shoud be? Not really, helpers have to calculate that everytime because of all the different hardware

**Comment by Crystal15118** [comment]
maybe we should just make it default to the answer the formula gives instead of having an AUTO value for it because it would stil be as helpful and would definitely avoid putting auto values for queue settings

**Comment by KingContaria** [comment]
> maybe we should just make it default to the answer the formula gives instead of having an AUTO value for it because it would stil be as helpful and would definitely avoid putting auto values for queue settings

This is what I meant by "I would be interested in is implementing reasonable defaults for Max Generating Seeds and Max Generating Seeds (Wall)".

> Making the user understand what it is just a sentence long, making them put it to what it shoud be? Not really, helpers have to calculate that everytime because of all the different hardware

This is only an issue because there is no very concise setup video yet (which is normal because features are still evolving and we don't have all the data yet), once that is done people will be able to calculate it themselves.
Also, having an AUTO option wouldn't solve people not knowing how much RAM to allocate, they wouldn't even be able to tell how big the queue is without checking making their wall 10x10 or checking F3. It also wouldn't help with users overshooting on RAM, which is arguably a bigger issue than undershooting.

I'm going to close this PR, I think a warning telling the user they have too little/too much RAM allocated with some tolerance makes more sense and is better for users knowing what's going on than an AUTO option

**Pull request closed without merging**
