### PR TITLE
Brief Readme

### PR DESCRIPTION
**Pull request by memerson12**
Just a basic readme to include basic info. If there is any interest, I can go a bit more in-depth. I wanted to gauge interest before I did all the work.

Let me know if any thoughts or if you are not interested in a readme :D

### CODE REVIEW

**Comment by memerson12** [comment]
Just realized another PR for a readme was opened an hour ago 🤦 
I can close this one if you want

**Comment by KingContaria** [comment]
The other one is mostly a brief summary which I'll probably merge when my requested changes are made, I'd be very much interested in a more in-depth one tho! :)

**Comment by KingContaria** [comment]
I'm not sure if you're in the discord yourself, I couldnt find you by your username, but there is also a dev discussion channel in place now if you wanna discuss anything or have questions for me to go more in-depth

**Comment by memerson12** [comment]
Not in the discord right now. I'll join and start working on a more in depth readme.

**Pull request closed without merging**
