### PR TITLE
Add Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by Kongbai-boi**
uploaded zh_cn.json

### CODE REVIEW

**Comment by KingContaria** [comment]
Thanks for the PR! :)
You'll need one more person verifying your translations, please check the newly added translations workflow: https://github.com/KingContaria/seedqueue/issues/66

**Comment by Kongbai-boi** [comment]
> Thanks for the PR! :) You'll need one more person verifying your translations, please check the newly added translations workflow: #66

Perxenate_Acid verified the translations in the discord

**Review by KingContaria — APPROVED** [review]
Checked, looks good to me

**Comment by KingContaria** [comment]
With 1.2 there is a couple of new/changed translation keys. I want to release this version fairly soon, if you don't have the time to make the edits i can do the renaming and merge the translations, new translations can be added later.

Renamed:
- "speedrunapi.config.seedqueue.option.backgroundPreviews" -> "speedrunapi.config.seedqueue.option.preparingPreviews"
- "speedrunapi.config.seedqueue.option.backgroundPreviews.description" -> "speedrunapi.config.seedqueue.option.preparingPreviews.description"

Added:
- "speedrunapi.config.seedqueue.option.preparingPreviews.value.-1": "Auto"
- "speedrunapi.config.seedqueue.option.resumeOnFilledQueue": "Resume On Filled Queue"
- "speedrunapi.config.seedqueue.option.resumeOnFilledQueue.description": "Whether to resume generating seeds after the queue is filled.\nThis overrides the Max World Generation % option after the queue capacity is filled."
- "seedqueue.key.scheduleJoin": "Schedule Instance"
- "seedqueue.key.scheduleAll": "Schedule All"

**Comment by KingContaria** [comment]
Sorry for this, one more update with 4 new translations was added. Like I said before, absolutely no pressure, I will still merge the translations without the updates if you dont have time. :)

Added:
- "speedrunapi.config.seedqueue.option.chunkMapFreezing": "Chunkmap Freezing"
- "speedrunapi.config.seedqueue.option.chunkMapFreezing.description": "Freezes the chunkmap after the set milliseconds. Useful for the \"Village Resetting\" strategy. Only applies to worlds on the wall that aren't locked."
- "speedrunapi.config.seedqueue.option.chunkMapFreezing.value": "%sms"
- "speedrunapi.config.seedqueue.option.chunkMapFreezing.value.-1": "OFF"

**Comment by Kongbai-boi** [comment]
done!

**Comment by KingContaria** [comment]
Thank you, will check later :)

**Pull request merged**
