### PR TITLE
Logging of SeedQueue Config file settings

### PR DESCRIPTION
**Pull request by Crystal15118**
Added feature mentioned in [#39](https://github.com/KingContaria/seedqueue/issues/39), information about the system is now printed when client is initialized (at the start when minecraft is launching). Information inside seedqueue.json and system information is printed whenever a benchmark ends (either by stopping or finishing).

### CODE REVIEW

**Comment by KingContaria** [comment]
I'm not a fan of the current logging on benchmark solution, I'd rather expose converting the current config to json in SpeedrunAPI and use that instead of reading the config file, I'm also not the biggest fan of just printing it as one big String.
Could you seperate out just the logging of system information on startup into a new PR, I would like to implement that but maybe think some more about how to best implement logging info after benchmarking.

**Comment by KingContaria** [comment]
Also for the future, don't put the issue link in the title of the PR, put it at the end of your message. That way github will automatically link the two.

**Comment by Crystal15118** [comment]
>  Could you seperate out just the logging of system information on startup into a new PR

let me do that

**Comment by Crystal15118** [comment]
> > Could you seperate out just the logging of system information on startup into a new PR
> 
> let me do that

@KingContaria opened new [pr](https://github.com/KingContaria/seedqueue/pull/51) which logs system information on startup.
Also can you please elaborate more on how i can improve the printing of config file to the log so its feasible to be pushed here?

**Comment by Crystal15118** [comment]
Changes for logging config settings will now be made in #70

**Pull request closed without merging**
